version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

networks:
  local:
    driver: 'bridge'
